[workspace]
release_always = false
pr_draft = false
pr_labels = ["release"]
git_release_draft = true
git_release_latest = false

[[package]]
name = "skil"
release = true
publish = true
semver_check = false
git_tag_name = "v{{ version }}"
git_release_enable = true
